---
- hosts: all
  tasks:
    - name: update the apt package 
      apt:
        update_cache: yes
    - name: install openjdk 11 or multiple package 
      apt:
        name: "{{ packages }}"
        state: present 
      vars:
        packages:
          - openjdk-11-jdk
          - tree
    - name: check the jdk version
      command: java --version
      register: javaversion #after executing the task i want to store the task value ina  varaibel
    - name: Print Java version
      debug:
        msg: "Jave version install: {{javaversion.stdout}}"
    - name: donwload latest release of maven and store in opt directory
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz
        dest: /opt
    - name: unarchive the maven tar file
      unarchive:
        src: /opt/apache-maven-3.8.5-bin.tar.gz
        dest: /opt
        remote_src: yes
    - name: rename the module which we have downloaded
      command: mv /opt/apache-maven-3.8.5 /opt/apache-maven
    - name: create a file apache maven 
      file:
        path: /etc/profile.d/apachemaven.sh
        state: touch

  