---
- hosts: all
  tasks:
    - name: update the apt package 
      apt:
        update_cache: yes
    - name: install openjdk 11 or multiple package 
      apt:
        name: "{{ packages }}"
        state: present 
      vars:
        packages:
          - openjdk-11-jdk
          - tree
  