---
- hosts: all
  tasks:
    - name: update the apt package 
      apt:
        update_cache: yes
    - name: install openjdk 11 or multiple package 
      apt:
        name: "{{ packages }}"
        state: present 
      vars:
        packages:
          - openjdk-11-jdk
          - tree
    - name: check the jdk version
      command: java --version
      register: javaversion #after executing the task i want to store the task value ina  varaibel
    - name: Print Java version
      debug:
        msg: "Jave version install: {{javaversion.stdout}}"
  